name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip python3-setuptools python3-wheel \
          build-essential git openjdk-17-jdk unzip zip \
          libssl-dev libffi-dev libsqlite3-dev zlib1g-dev \
          libbz2-dev libreadline-dev libncurses5-dev libgdbm-dev liblzma-dev \
          libtool automake autoconf pkg-config

    - name: Upgrade pip and install buildozer
      run: |
        python3 -m pip install --upgrade pip setuptools wheel Cython virtualenv buildozer

    - name: Preinstall setuptools/wheel/Cython for python-for-android
      run: |
        pip install --upgrade pip setuptools wheel Cython

    # 🟢 NEW: Install Android SDK Build Tools and set up environment
    - name: Install Android SDK Build Tools
      env:
        ANDROID_SDK_ROOT: /opt/android-sdk
      run: |
        sudo mkdir -p $ANDROID_SDK_ROOT
        sudo chown $USER $ANDROID_SDK_ROOT
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        mv cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vibrotactile-apk
        path: bin/*.apk
