name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_HOME: /opt/android-sdk
      ANDROIDSDK: /opt/android-sdk
      PATH: /opt/android-sdk/platform-tools:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:${{ env.PATH }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip python3-setuptools python3-wheel \
          build-essential git openjdk-17-jdk unzip zip \
          libssl-dev libffi-dev libsqlite3-dev zlib1g-dev \
          libbz2-dev libreadline-dev libncurses5-dev libgdbm-dev liblzma-dev \
          libtool automake autoconf pkg-config

    - name: Upgrade pip and install buildozer
      run: |
        python3 -m pip install --upgrade pip setuptools wheel Cython virtualenv buildozer

    - name: Preinstall setuptools/wheel/Cython for python-for-android
      run: |
        pip install --upgrade pip setuptools wheel Cython

    - name: Install Android SDK Command Line Tools and Build Tools
      run: |
        sudo mkdir -p /opt/android-sdk
        sudo chown $USER:$USER /opt/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d /opt/android-sdk/
        mkdir -p /opt/android-sdk/cmdline-tools
        mv /opt/android-sdk/cmdline-tools /opt/android-sdk/cmdline-tools/latest || true
        mv /opt/android-sdk/cmdline-tools-latest /opt/android-sdk/cmdline-tools/latest || true
        yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk --licenses
        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        echo "Android SDK installed"

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: /opt/android-sdk
        ANDROID_HOME: /opt/android-sdk
        ANDROIDSDK: /opt/android-sdk
        PATH: /opt/android-sdk/platform-tools:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:${{ env.PATH }}
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vibrotactile-apk
        path: bin/*.apk
